version: "3"
services:
  vscode-server:
    image: codercom/code-server:1.621
    container_name: vscode-server
    restart: always
    stdin_open: true
    tty: true
    command: --allow-http --no-auth
    ports:
      - "127.0.0.1:8443:8443"
    volumes:
      - ${PWD}:/home/coder/project
    
      
      
